{
 "title": "shelly",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Apparent Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "shelly_total_aprt_power", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Напряжение в сети",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "shelly_voltage", "legendFormat": "напряжение {{phase}}" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "shelly_current", "legendFormat": "ток на фазе {{phase}}" }
   ]
  }
 ]
}